AWSTemplateFormatVersion: "2010-09-09"
Description: Cost-effective scheduled Fargate task for the scraper using Secrets Manager for Postgres credentials

Parameters:
  ECRImageUri:
    Type: String
    Description: ECR image URI (e.g. 123456789012.dkr.ecr.us-west-2.amazonaws.com/scraper:latest)

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC for the Fargate task

  SubnetIds:
    Type: CommaDelimitedList
    Description: Comma-separated list of subnet IDs (public subnets recommended to avoid NAT costs)

  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security group allowing egress to RDS

  SecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret with Postgres credentials

  ScheduleExpression:
    Type: String
    Default: rate(20 minutes)
    Description: EventBridge schedule expression (e.g. rate(24 hours) or cron(0 8 * * ? *))

  Cpu:
    Type: Number
    Default: 256
    Description: Fargate CPU units

  Memory:
    Type: Number
    Default: 512
    Description: Fargate memory (MiB)

  AssignPublicIp:
    Type: String
    Default: ENABLED
    AllowedValues:
      - ENABLED
      - DISABLED
    Description: Assign a public IP (ENABLED for public subnets, DISABLED for private subnets)

  UseFargateSpot:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Use Fargate Spot capacity for lower cost (may be interrupted)

  LogRetentionDays:
    Type: Number
    Default: 7
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
    Description: CloudWatch log retention in days

Conditions:
  UseSpot: !Equals [!Ref UseFargateSpot, "true"]

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${AWS::StackName}-cluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-scraper-task-exec
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: ReadSecretsManager
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref SecretArn

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AWS::StackName}
      RetentionInDays: !Ref LogRetentionDays

  ScraperTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: ScraperTask
      Cpu: !Ref Cpu
      Memory: !Ref Memory
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: scraper
          Image: !Ref ECRImageUri
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub /ecs/${AWS::StackName}
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: scraper
          Secrets:
            - Name: POSTGRES_USER
              ValueFrom: !Sub "${SecretArn}:username::"
            - Name: POSTGRES_PASSWORD
              ValueFrom: !Sub "${SecretArn}:password::"
            - Name: POSTGRES_HOST
              ValueFrom: !Sub "${SecretArn}:host::"
            - Name: POSTGRES_PORT
              ValueFrom: !Sub "${SecretArn}:port::"
            - Name: POSTGRES_DB
              ValueFrom: !Sub "${SecretArn}:dbname::"

  EventsInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-events-invoke-ecs-task
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowECSRunTask
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecs:RunTask
                Resource: !Ref ScraperTaskDefinition
                Condition:
                  ArnEquals:
                    ecs:cluster: !GetAtt ECSCluster.Arn
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource:
                  - !GetAtt TaskExecutionRole.Arn

  ScraperScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${AWS::StackName}-schedule
      ScheduleExpression: !Ref ScheduleExpression
      State: ENABLED
      Targets:
        - Id: ScraperTarget
          Arn: !GetAtt ECSCluster.Arn
          RoleArn: !GetAtt EventsInvokeRole.Arn
          EcsParameters:
            TaskDefinitionArn: !Ref ScraperTaskDefinition
            PlatformVersion: LATEST
            NetworkConfiguration:
              AwsVpcConfiguration:
                Subnets: !Ref SubnetIds
                SecurityGroups:
                  - !Ref SecurityGroupId
                AssignPublicIp: !Ref AssignPublicIp
            LaunchType: !If [UseSpot, !Ref "AWS::NoValue", FARGATE]
            CapacityProviderStrategy: !If
              - UseSpot
              - - CapacityProvider: FARGATE_SPOT
                  Weight: 1
              - !Ref "AWS::NoValue"

Outputs:
  TaskDefinitionArn:
    Value: !Ref ScraperTaskDefinition
  LogGroupName:
    Value: !Sub /ecs/${AWS::StackName}
  ScheduleExpression:
    Value: !Ref ScheduleExpression
